### ISSUE TITLE
Trailing slashes '/' in dataset URIs

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/ld.cat#10]
Should we promote the use of hash or slash URIs? 

Document preference in https://github.com/CSIRO-enviro-informatics/loci.cat/wiki/Rules-for-Loc-I-datasets

**Comment by dr-shorthair** [comment]
For _datasets_ I would strongly encourage / URIs, so that you can cleanly address/de-reference individual entities. 

For small vocabularies (e.g. ontologies) # URIs are ok and are often used - there is a mixture of practice in the community and we don't control it because we re-use (import) some external vocabularies that use both patterns.

**Comment by dr-shorthair** [comment]
But there is also a separate issue that most of the individual registers (datasets) in the cache are denoted by URIs with a trailing / (slash). This is not a completely unusual pattern, particularly for resources whose URI is the root of some member resources (similar to directories and files) but it is probably worth ensuring that the URI service does catch URIs with and without a trailing slash and redirect it to the same thing. 

In practice that probably means that **no-trailing-slash** is probably the canonical URI, and **trailing-slash** gets redirected to no-trailing-slash. (Redirecting the other direction is a harder rule to write.)

**Comment by jyucsiro** [comment]
@dr-shorthair can we close this issue? i think this is resolved now.
