### ISSUE TITLE
Document Loc-I dataset URI naming convention

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/ld.cat#11]
What is the expectations around naming conventions for Loc-I datasets?

Do we use system/dataset level IDs or preferred names/labels for the URIs?

Document this at https://github.com/CSIRO-enviro-informatics/loci.cat/wiki/Rules-for-Loc-I-datasets

**Comment by dr-shorthair** [comment]
I would have no objection to using IDs (codes) consistently, including for the small sets (states). 
If you have to look at 'labels' for some, might as well be for all.

**Comment by dr-shorthair** [comment]
In fact I'm not at all sure that having the type hidden in the URI e.g. `http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel2/308041528` is necessary, given that we can easily check that `<http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel2/308041528> rdf:type <http://linked.data.gov.au/def/asgs#StatisticalAreaLevel2>`. 

Probably `http://linked.data.gov.au/dataset/asgs2016/308041528` is more robust. (I see that `308041528` is the `sa2Maincode2016` and also the  `statisticalArea2Sa29DigitCode`)

**Comment by jyucsiro** [comment]
For ASGS it seems like `/dataset/asgs2016/<id>` is robust and the type isn't required in its URI naming convention. This is because the ID is robust across types.

For other cases, embeding the feature type name/id in the URI may be needed where ID is not robust across types? 
e.g. FeatureType A has id set (1, 2, 3) and FeatureType B has id set (1, 2, 3...)

**Comment by dr-shorthair** [comment]
+1 you are focussing on the key issue.

**Comment by shaneseaton** [comment]
I like namespacing the Id's with their type. I agree it is not essential for the ASGS, but it's probably an outlier. I can easily imagine Id repeating across most datatypes. Esp with a basic numbering system. And because of that, and our need to be consistent in the datasets we produce. I would vote for keeping the namespacing practice in all datasets, it allows more flexibility down the road.

**Comment by dr-shorthair** [comment]
Including the type in the URI was the pattern originally proposed by the UK Government LDWG. 
AGLDWG followed along. It is usually harmless, however, in practice many resources have multiple types (at the very least they are also members of the superclass). And it is not impossible to imagine that the resource denoted by a URI could be re-classified. By embedding the type in the URI your flexibility in managing some workflows is compromised.

**Comment by dr-shorthair** [comment]
Mind you, in the Place Names dataset the feature-type is an intrinsic part of the identity - the same label often applies to multiple features of different types (school, suburb, railway station ...) . In this case there is a well-governed feature-type catalogue alongside the dataset, so the type probably does need to be in the identifier.

**Comment by dr-shorthair** [comment]
Also see discussion in https://github.com/CSIRO-enviro-informatics/asgs-dataset/issues/6 

Ideal pattern: 

| Class | Register | Example individual |
| --- | --- | --- |
|  http://linked.data.gov.au/def/asgs#MeshBlock | http://linked.data.gov.au/dataset/asgs2016/meshblock |  http://linked.data.gov.au/dataset/asgs2016/meshblock/50259230000 |
| http://linked.data.gov.au/def/asgs#StatisticalAreaLevel1 | http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel1 | http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel1/50102100504 | 
| http://linked.data.gov.au/def/asgs#StatisticalAreaLevel2 | http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel2 | http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel2/308031218 |
| http://linked.data.gov.au/def/asgs#StatisticalAreaLevel3 | http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel3 | http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel3/80106 |
| http://linked.data.gov.au/def/asgs#StatisticalAreaLevel4 | http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel4 | http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel4/207 |
| http://linked.data.gov.au/def/asgs#StateOrTerritory | http://linked.data.gov.au/dataset/asgs2016/stateorterritory | http://linked.data.gov.au/dataset/asgs2016/stateorterritory/2 |
| http://linked.data.gov.au/def/asgs#Country | http://linked.data.gov.au/dataset/asgs2016/country | http://linked.data.gov.au/dataset/asgs2016/country/61 |

But in practice the last line is 

| Class | Register | Instance |
| --- | --- | --- |
| http://linked.data.gov.au/def/asgs#Country | http://linked.data.gov.au/dataset/asgs2016/australia | http://linked.data.gov.au/dataset/asgs2016/australia/036 |

**Comment by dr-shorthair** [comment]
I have written up the current state here: https://github.com/CSIRO-enviro-informatics/loci.cat/wiki/Rules-for-Loc-I-datasets#uri-naming-conventions 

I found two inconsistencies in the conventions for ASGS/G-NAF/GeoFabric: 

1. The register and individual URIs for Australia within ASGS include the token `/australia` instead of the class-name `/country`
2. Within the register and individual URIs the class-name is folded to **lowerCamelCase** for G-NAF and **lowercase** for ASGS and GeoFabric.

**Comment by jyucsiro** [comment]
> But in practice the last line is
> 
> Class	Register	Instance
> http://linked.data.gov.au/def/asgs#Country	http://linked.data.gov.au/dataset/asgs2016/australia	http://linked.data.gov.au/dataset/asgs2016/australia/036

I recall someone mentioning that there is a register of "australia" because there may be multiple definitions (spatially or otherwise) of "Australia". What to we do in your proposed ideal pattern for Country?

**Comment by dr-shorthair** [comment]
That's not how I see                   it. 
The register name matches the top class from the ASGS documentation: https://www.abs.gov.au/websitedbs/D3310114.nsf/home/Australian+Statistical+Geography+Standard+(ASGS) 
while the ontology class name matches the type. 
The issue is because the diagram is inconsistent, in that all the boxes are labelled with class names except the top one which is reflects the name of one individual from the inferred class 'Country'. It is becasue, of course, in our context this class only has one member. It is really a quirk of the fact that the ABS documentation is not a formal notation. 

It might be a problem if a rule-based system is used to (re-)generate the RDF data, and thee is no exception added for this individual register.
